spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: pack-service
              uri: lb://pack-service
              predicates:
                - Path=/api/packs/**
              filters:
                - RewritePath=/api/packs/(?<segment>.*), /${segment}

            - id: appointment-service
              uri: lb://appointment-service
              predicates:
                - Path=/api/appointments/**
              filters:
                - RewritePath=/api/appointments/(?<segment>.*), /${segment}

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/users/(?<segment>.*), /${segment}

            - id: plan-service
              uri: lb://plan-service
              predicates:
                - Path=/api/plans/**
              filters:
                - RewritePath=/api/plans/(?<segment>.*), /${segment}

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: false

  profiles:
    active: default

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, gateway
