server:
  port: 8081

spring:
  application:
    name: appointment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/appointments

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
