server:
  port: 8082

spring:
  application:
    name: appointment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/appointments
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
