server:
  port: 8081

spring:
  application:
    name: Pack-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/packs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
