server:
  port: 8081

spring:
  application:
    name: Pack-Service
  datasource:
    url: jdbc:h2:mem:packdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
