server:
  port: 8084

spring:
  application:
    name: plan-service
  profiles:
    active: default
  config:
    import: configserver:http://config-server:8888
  data:
    mongodb:
      uri: mongodb://mongo:27017/plandb
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
