spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb  # Replace with your actual Mongo URI if needed

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
