spring:
  application:
    name: user-service

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
