server:
  port: 8083

spring:
  application:
    name: user-service
  profiles:
    active: default
  config:
    import: configserver:http://config-server:8888
  data:
    mongodb:
      uri: mongodb://mongo:27017/userdb

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
